(* Generated by the SAL Theorem to Isabelle Translator *)
(* Version 1.2 released 21 June 2021 *)
theory linked_inTheorems
imports "EFSM.EFSM_LTL" Linked_In Linked_In

begin

lemma LTL_neverDetailed :
  "((label_eq ''login'' aand
      input_eq [Str ''free'']) impl
      nxt (alw ((label_eq ''pdf'' aand
      check_exp (Eq (V (Ip 0)) (L (Str ''otherID'')))) impl
      not (nxt (output_eq [Some (Str
      ''detailed_pdf_of_otherID'')])))))
(watch linkedIn trace)"
using LTL_neverDetailed by blast

end


