(* Generated by the SAL Theorem to Isabelle Translator *)
(* Version 1.2 released 21 June 2021 *)
theory coin_tea_brokenTheorems
imports "EFSM.EFSM_LTL" Coin_Tea_Broken Coin_Tea_Broken

begin

lemma LTL_label_vend_not_2 :
  "(label_eq ''vend'' impl not (ev (state_eq (Some 2))))
(watch drinks trace)"
using LTL_label_vend_not_2 by blast

lemma LTL_init_makes_r_1_zero :
  "((label_eq ''init'' aand
      input_eq []) impl
      nxt (check_exp (Eq (V (Rg 1)) (L (Num 0)))))
(watch drinks trace)"
using LTL_init_makes_r_1_zero by blast

lemma LTL_vend_no_coin :
  "(nxt (label_eq ''vend'' aand
      input_eq []) impl not (ev (state_eq (Some 2))))
(watch drinks trace)"
using LTL_vend_no_coin by blast

lemma LTL_invalid_gets_stuck_2 :
  "((nxt (not (label_eq ''coin'' aand input_eq [])) aand
      nxt (not (label_eq ''vend'' aand
      input_eq []))) impl not (ev (state_eq (Some 2))))
(watch drinks trace)"
using LTL_invalid_gets_stuck_2 by blast

lemma LTL_must_pay_correct :
  "(ev (state_eq (Some 2)) impl
      (not (label_eq ''vend'') suntil label_eq ''coin''))
(watch drinks trace)"
using LTL_must_pay_correct by blast

lemma LTL_must_pay_correct_bracketed :
  "(ev (state_eq (Some 2)) impl
      (not (label_eq ''vend'') suntil label_eq ''coin''))
(watch drinks trace)"
using LTL_must_pay_correct_bracketed by blast

end


