(* Generated by the Dot to Isabelle Translator *)
(* Version 1.5 released 25 June 2021 *)
theory XXDOTXXCoin_Tea_Broken
imports "EFSM.EFSM"
begin

definition "init" :: "transition" where
"init \<equiv> \<lparr>
      Label = STR ''init'',
      Arity = 0,
      Guards = [],
      Outputs = [],
      Updates = [
            (1, (L (Num 0)))
      ]
\<rparr>"

definition "coin" :: "transition" where
"coin \<equiv> \<lparr>
      Label = STR ''coin'',
      Arity = 0,
      Guards = [],
      Outputs = [],
      Updates = [
            (1, (Plus (V (R 1)) (L (Num 1))))
      ]
\<rparr>"

definition "vend" :: "transition" where
"vend \<equiv> \<lparr>
      Label = STR ''vend'',
      Arity = 0,
      Guards = [
            (Ge (V (R 1)) (L (Num 0)))
      ],
      Outputs = [
            (L (Str ''tea''))
      ],
      Updates = []
\<rparr>"

definition "coin_tea_broken" :: "transition_matrix" where
"coin_tea_broken \<equiv> {|
      ((0, 1), init),
      ((1, 1), coin),
      ((1, 2), vend)
|}"

lemmas transitions =
      init_def
      coin_def
      vend_def

end
