(* Generated by the Dot to Isabelle Translator *)
(* Version 1.2 released 21 June 2021 *)
theory XXXCoin_Tea
imports "EFSM.EFSM" Coin_Tea
begin

definition "init" :: "transition" where
"init \<equiv> \<lparr>
      Label = STR ''init'',
      Arity = 0,
      Guards = [],
      Outputs = [],
      Updates = [
            (1, (L (Num 0)))
      ]
\<rparr>"

definition "coin" :: "transition" where
"coin \<equiv> \<lparr>
      Label = STR ''coin'',
      Arity = 0,
      Guards = [],
      Outputs = [],
      Updates = [
            (1, (Plus (V (R 1)) (L (Num 1))))
      ]
\<rparr>"

definition "vend" :: "transition" where
"vend \<equiv> \<lparr>
      Label = STR ''vend'',
      Arity = 0,
      Guards = [
            (Gt (V (R 1)) (L (Num 0)))
      ],
      Outputs = [
            (L (Str ''tea''))
      ],
      Updates = []
\<rparr>"

definition "coin_tea" :: "transition_matrix" where
"coin_tea \<equiv> {|
      ((0, 1), init),
      ((1, 1), coin),
      ((1, 2), vend)
|}"

lemmas transitions = select_def
      init_def
      coin_def
      vend_def

lemma "coin_tea = drinks"
  by (simp add: drinks_def coin_tea_def transitions Coin_Tea.transitions)

end
