(* Generated by the SAL to Isabelle Translator *)
(* Version 1.5 released 25 June 2021 *)

theory drinks_machine
imports "EFSM.EFSM_LTL"
begin

declare One_nat_def [simp del]
declare ltl_step_alt [simp]

definition select :: "transition" where
"select \<equiv> \<lparr>
    Label = (STR ''select''),
    Arity = 1,
    Guards = [],
    Outputs = [],
    Updates = [
      (1, (V (I 0))),
      (2, (L (Num 0)))
    ]
\<rparr>"

definition coin :: "transition" where
"coin \<equiv> \<lparr>
    Label = (STR ''coin''),
    Arity = 1,
    Guards = [],
    Outputs = [
      (Plus (V (R 2)) (V (I 0)))
    ],
    Updates = [
      (1, (V (R 1))),
      (2, (Plus (V (R 2)) (V (I 0))))
    ]
\<rparr>"

definition vend :: "transition" where
"vend \<equiv> \<lparr>
    Label = (STR ''vend''),
    Arity = 0,
    Guards = [
      (Ge (V (R 2)) (L (Num 100)))
    ],
    Outputs = [
      (V (R 1))
    ],
    Updates = [
      (1, (V (R 1))),
      (2, (V (R 2)))
    ]
\<rparr>"

definition vend_fail :: "transition" where
"vend_fail \<equiv> \<lparr>
    Label = (STR ''vend''),
    Arity = 0,
    Guards = [
      (Lt (V (R 2)) (L (Num 100)))
    ],
    Outputs = [],
    Updates = [
      (1, (V (R 1))),
      (2, (V (R 2)))
    ]
\<rparr>"


definition drinks :: "transition_matrix" where
"drinks \<equiv> {|
    ((0, 1), select),
    ((1, 1), coin),
    ((1, 2), vend),
    ((1, 1), vend_fail)
  |}"
  
  
lemmas transitions =
  select_def
  coin_def
  vend_def
  vend_fail_def
  
  
end
